### ISSUE TITLE
Support for toggling AppDelegate method swizzling

### ISSUE THREAD

**Issue by irbisdev** [pushy/pushy-react-native#79]
Can you add support for toggling AppDelegate method swizzling like in [pushy-sdk-ios](https://github.com/pushy-me/pushy-sdk-ios/blob/master/PushySDK/Pushy.swift#L567)?

**Comment by pushy** [comment]
Hi @irbisdev,
Absolutely. We've just released version `1.0.24` of the Pushy RN SDK which adds support for `Pushy.toggleMethodSwizzling()`.

Run the following commands in the root directory of your project to update to the latest `pushy-react-native` package from `npm` and relink the iOS module:

```
npx react-native unlink pushy-react-native
npm install pushy-react-native@1.0.24 --save
npx react-native link pushy-react-native
```

Then, call `Pushy.toggleMethodSwizzling(true)` in `App.js` before `Pushy.listen()`:

```
// Disable AppDelegate method swizzling
Pushy.toggleMethodSwizzling(false)
```
For the SDK to continue working properly after disabling method swizzling, please override the following APNs methods in your `ios/AppDelegate.m` implementation file, making sure to invoke the Pushy iOS SDK at the end of each of them, by adding the following APNs method overrides:

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [[PushyModule getSharedPushyInstance] application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
  [[PushyModule getSharedPushyInstance] application:application didFailToRegisterForRemoteNotificationsWithError:error];
}

- (void) applicatiogetSharedPushyInstancen:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
  [[PushyModule getSharedPushyInstance] application:application didReceiveRemoteNotification:userInfo];
}

- (void) application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  [[PushyModule getSharedPushyInstance] application:application didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
```

Please let us know if you face any issues.

**Comment by AlexeyNovikov** [comment]
@pushy Hey guys, after we called Pushy.toggleMethodSwizzling(false) Pushy.setNotificationClickListener(async (data: any) => {}) stopped receiving notifications. Do you have an idea what could go wrong?

**Comment by pushy** [comment]
Hi @AlexeyNovikov,
We'd be glad to assist.

Please add the following line of code to your `ios/app/AppDelegate.m` file, inside the `didFinishLaunchingWithOptions` method:

```
[UNUserNotificationCenter currentNotificationCenter].delegate = [PushyModule getSharedPushyInstance];
```

Please also add the following import to the top of the file:

```
#import <UserNotifications/UserNotifications.h>
```

That should resolve the issue. Please let us know if you face any difficulties.

**Comment by AlexeyNovikov** [comment]
Thanks for the quick reply! We'll test it tomorrow. The only question is should we remove 4 delegate methods that you mentioned earlier? Since now the whole PushyModule object becomes a delegate.

**Comment by pushy** [comment]
Hi @AlexeyNovikov,
You're most welcome! 

Please do not remove the 4 APNs delegate methods - they are still needed. 

While we are setting the `UNUserNotificationCenter` delegate using the above line of code, the `UNUserNotificationCenter` delegate is only responsible for `UNUserNotificationCenter` events (such as in-app notification banner display & click handling). The APNs callbacks are not directed there. They are only directed to a `UIApplicationDelegate`.

**Comment by AlexeyNovikov** [comment]
<img width="777" alt="Screenshot 2022-09-15 at 20 11 04" src="https://user-images.githubusercontent.com/30009270/190468011-e3d75be1-318d-42d1-a207-15032dcbbf58.png">
It turns out we already set AppDelegate as a delegate of UNUserNotificationCenter. More than that, setting PushyModule instance as the delegate shows a warning. Can we proxy required AppDelegate callbacks to PushyModule instance methods as we did for UIApplicationDelegate?

**Comment by pushy** [comment]
Hi @AlexeyNovikov,
Absolutely, that's another option if you'd like your own `AppDelegate` to receive `UNUserNotificationCenterDelegate` callbacks.

Remove this line of code if you haven't already:

```
[UNUserNotificationCenter currentNotificationCenter].delegate = [PushyModule getSharedPushyInstance];
```

Add the following method override to `AppDelegate.m`:

```
- (void)userNotificationCenter:(UNUserNotificationCenter* )center
        willPresentNotification:(UNNotification* )notification
        withCompletionHandler:(void (^)
        (UNNotificationPresentationOptions options))completionHandler {
  [[PushyModule getSharedPushyInstance] userNotificationCenter:center willPresentNotification:notification withCompletionHandler:completionHandler];
}
```

This will require updating to the newest version of the Pushy RN SDK which adds a definition for the `willPresentNotification` method to the interface. Please run the following commands in the root directory of your project to update to the latest `pushy-react-native` package from `npm` and relink the iOS module:

```
npx react-native unlink pushy-react-native
npm install pushy-react-native@1.0.25 --save
npx react-native link pushy-react-native
```

Please let us know if you face any issues.

**Comment by AlexeyNovikov** [comment]
Hey guys. Sorry to bother you again. But can you add this definition
```
- (void)userNotificationCenter:(UNUserNotificationCenter* _Nonnull)center
didReceiveNotificationResponse:(UNNotificationResponse* _Nonnull)response
         withCompletionHandler:(void (^_Nonnull)(void))completionHandler;
```
to the `PushyModule.h` file?
We want `Pushy.setNotificationClickListener()` to work again after switching swizzling off and I suppose that what we need to do in order to achieve that. And thanks for your patience to our case :pray:

**Comment by pushy** [comment]
Hi @AlexeyNovikov,
Sure thing, we've exposed all methods in commit https://github.com/pushy/pushy-react-native/commit/75dcfd0d32c09c7fdcb170e6ece7e285157707d6 and published a new version.

Run the following commands in the root directory of your project to update to the latest `pushy-react-native` package from `npm` and relink the iOS module:

```
npx react-native unlink pushy-react-native
npm install pushy-react-native@1.0.26 --save
npx react-native link pushy-react-native
```

Please let us know if you face any issues.
