### ISSUE TITLE
can not link with react native 0.70.1

### ISSUE THREAD

**Issue by artsztu27** [pushy/pushy-react-native#80]
npx react-native link pushy-react-native
error: unknown command 'link'

my version info is bellow:

```
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 538.18 MB / 16.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.09.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.1 => 0.70.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by pushy** [comment]
Hi @artsztu27,
Thanks for reporting this.

Indeed, in version `0.70.1` of React Native, it appears the `react-native link` command has been finally removed completely. Not to worry - the Pushy React Native SDK already supports autolinking. We've just tested it again on a new `0.70.1` project and can confirm it works. We've removed this command from the [Pushy React Native integration docs](https://pushy.me/docs/additional-platforms/react-native) as it is no longer needed.

Please proceed with the integration by running the following command to install the PushyRN Cocoapods dependency:

```
cd ios && pod install
```

And proceed with following the rest of the instructions [in our docs](https://pushy.me/docs/additional-platforms/react-native).
