### ISSUE TITLE
Pushy.toggleFCM(true) not available with latest version

### ISSUE THREAD

**Issue by affansk** [pushy/pushy-react-native#82]
Pushy.toggleFCM(true) not available with latest version

**Comment by pushy** [comment]
Hi @affansk,
Thanks for reaching out. We'd be glad to assist.

We've just released version `1.0.31` of the Pushy RN SDK which resolves the issue with `Pushy.toggleFCM()` erroring out when running your React Native app on iOS. As a reminder, `Pushy.toggleFCM()` is an Android-only feature.

Run the following commands in the root directory of your project to update to the latest `pushy-react-native` package from `npm` and relink the iOS module:

```
npx react-native unlink pushy-react-native
npm install pushy-react-native@1.0.31 --save
npx react-native link pushy-react-native
```

Next, please make sure you're importing both version `1.0.89` of the Pushy Android SDK and version `1.0.18` of the `Pushy React Native Android SDK` by updating the following dependencies to your `android/app/build.gradle`, within the `dependencies {}` declaration:
```
// Pushy SDK for Android
implementation 'me.pushy:sdk:1.0.89'

// Pushy SDK for React Native Android
implementation 'me.pushy:sdk-react-native:1.0.18'
```

Please let us know if this resolves your issue, or if you require any further assistance.
