### ISSUE TITLE
setNotificationClickListener is invoked everytime

### ISSUE THREAD

**Issue by johnvalle** [pushy/pushy-react-native#86]
Once I click on notifications from background state, the callback from `setNotificationClickListener` is called properly. However, after that, the callback is called every time the app is refreshed, even if no actual `click` happened. I added a log inside the callback function and it shows me the notification data that initially triggered the callback.

Pushy SDK: 1.0.90
Pushy SDK React Native: 1.0.19
Pushy React Native: 1.0.31
Device: Samsung S21 Ultra

**Comment by pushy** [comment]
Hi @johnvalle,
Thanks for reaching out. We'd be glad to assist.

We've just released version `1.0.32` of the Pushy RN SDK which resolves this issue via commit https://github.com/pushy/pushy-react-native/commit/c50b29e609e583d5ae8dafa712cda8d3991893df.

Run the following commands in the root directory of your project to update to the latest `pushy-react-native` package from `npm` and relink the iOS module:

```
npx react-native unlink pushy-react-native
npm install pushy-react-native@1.0.32 --save
npx react-native link pushy-react-native
```

Please let us know if this resolves your issue, or if you require any further assistance.
