### ISSUE TITLE
 ERROR  Pushy native module not loaded, please include the PushyPackage() declaration within your app's MainApplication.getPackages() implementation.

### ISSUE THREAD

**Issue by Taribi-Isaac** [pushy/pushy-react-native#96]
I am trying to use Pushy in my React Native Expo project, I followed the Docs carefully but ran into this error.
Is there a way to resolve this in In Expo?

**Comment by pushy** [comment]
Hi @Taribi-Isaac,
Thanks for reaching out. We'd be glad to assist.

To resolve the issue, please make sure to load the native `PushyPackage` within your `MainApplication.kt` class by replacing this line of code in the `getPackages()` method implementation:

Find:
```
return PackageList(this).packages
```

Replace with:

```
return PackageList(this).packages.apply {
    add(me.pushy.sdk.react.PushyPackage());
}
```

Please let us know if there's anything else we can help with.
